# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [15]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.19.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
null_vector = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
print('Size of the array: ', null_vector.size)
print('Memory size of one array element in by element in bytes: ', null_vector.itemsize)
print('Memory size of numpy array in bytes: ', null_vector.size * null_vector.itemsize)
print('Memory size of numpy array in bytes using simplified method: ', null_vector.nbytes)

Size of the array:  10
Memory size of one array element in by element in bytes:  8
Memory size of numpy array in bytes:  80
Memory size of numpy array in bytes using simplified method:  80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
x = (np.arange(10) == 4).astype(int)
print('Null vector w/ expection: ', x)
print('Checking Location exception value: ', x[4])


Null vector w/ expection:  [0 0 0 0 1 0 0 0 0 0]
Checking Location exception value:  1


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
x = np.arange(50).astype(int)[10:50]
z = np.arange(10, 50, dtype=int)
print(x)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
a = np.arange(9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [5]:
x = [1, 2, 0, 0, 4, 0]
nparray = np.asarray(x)

print(nparray)
for x in range(len(nparray)):
    if nparray[x] != 0:
        print(x, end=' ')

[1 2 0 0 4 0]
0 1 4 

#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
a = np.random.random((3,3,3))
print(a)

[[[0.09701318 0.46391792 0.88579915]
  [0.06887142 0.8255912  0.77015993]
  [0.14835756 0.11349266 0.6826758 ]]

 [[0.19428162 0.52094672 0.1846562 ]
  [0.71635503 0.20898044 0.32433353]
  [0.75467952 0.94331382 0.68295487]]

 [[0.37903635 0.96614809 0.80372161]
  [0.91530086 0.72141142 0.19726922]
  [0.32170144 0.23005138 0.78165247]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
a = np.random.random((10,10))
print(a)
print('Max: ', np.max(a))
print('Min: ', np.min(a))

[[0.21753909 0.80917101 0.37686129 0.34135734 0.45880699 0.09008457
  0.69869587 0.54937797 0.56650371 0.87331903]
 [0.68507345 0.061159   0.54847191 0.87919715 0.58221516 0.01783698
  0.07426493 0.66423913 0.58908238 0.30304513]
 [0.90312608 0.19788341 0.70561877 0.23803399 0.6272202  0.99968926
  0.17718461 0.30950504 0.79703843 0.65696335]
 [0.57939892 0.83013393 0.91586037 0.95544601 0.15742835 0.30251974
  0.88256219 0.33665014 0.54844076 0.52384066]
 [0.56101185 0.42061253 0.56722777 0.39599021 0.28888928 0.96827413
  0.49918314 0.50549187 0.87593456 0.70878368]
 [0.24086379 0.21089671 0.2248793  0.11709292 0.98725819 0.35755194
  0.1743592  0.1283014  0.50232341 0.8059222 ]
 [0.33951753 0.48020409 0.9920704  0.5509232  0.89716356 0.86121122
  0.79626237 0.01249146 0.78129944 0.77097194]
 [0.11600232 0.3872579  0.15727094 0.1108979  0.68907768 0.28969281
  0.57800329 0.71021705 0.79643823 0.16061085]
 [0.37679615 0.52664967 0.14250514 0.5483143  0.24390988 0.50003974
  0.21556081

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
a = np.random.random(30)
print(a)
b = np.mean(a)
print('Mean: ', b)

[0.10552886 0.64578239 0.42699744 0.11690463 0.45394263 0.25792723
 0.69772096 0.46213796 0.18389679 0.6003212  0.94575987 0.41758124
 0.6071605  0.38023547 0.20622685 0.62773154 0.92421327 0.72506993
 0.04341164 0.02081474 0.51779734 0.70879193 0.06083663 0.22891178
 0.38575913 0.53532319 0.56747767 0.0081607  0.98849571 0.8605525 ]
Mean:  0.4570490564119039


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
x = np.ones((3,3))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [66]:
np.tril(np.random.randint(1,5, size=(5,5)),-1)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [2, 4, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [2, 1, 4, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
a = np.ones((8, 8))
for x in range(8):
    for y in range(8):
        if ((x + y) % 2 == 0):
            a[x][y] = 0
        else:
            a[x][y] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
a = np.zeros((6,7,8))
bean_counter = 0
for x in range(6):
    for y in range(7):
        for z in range(8):
            a[x][y][z] = bean_counter
            bean_counter += 1
            if a[x][y][z] == 100:
                print("100th element Coordinates X: ", x, " Y: ", y, " Z: ", z)
print(a)

100th element Coordinates X:  1  Y:  5  Z:  4
[[[  0.   1.   2.   3.   4.   5.   6.   7.]
  [  8.   9.  10.  11.  12.  13.  14.  15.]
  [ 16.  17.  18.  19.  20.  21.  22.  23.]
  [ 24.  25.  26.  27.  28.  29.  30.  31.]
  [ 32.  33.  34.  35.  36.  37.  38.  39.]
  [ 40.  41.  42.  43.  44.  45.  46.  47.]
  [ 48.  49.  50.  51.  52.  53.  54.  55.]]

 [[ 56.  57.  58.  59.  60.  61.  62.  63.]
  [ 64.  65.  66.  67.  68.  69.  70.  71.]
  [ 72.  73.  74.  75.  76.  77.  78.  79.]
  [ 80.  81.  82.  83.  84.  85.  86.  87.]
  [ 88.  89.  90.  91.  92.  93.  94.  95.]
  [ 96.  97.  98.  99. 100. 101. 102. 103.]
  [104. 105. 106. 107. 108. 109. 110. 111.]]

 [[112. 113. 114. 115. 116. 117. 118. 119.]
  [120. 121. 122. 123. 124. 125. 126. 127.]
  [128. 129. 130. 131. 132. 133. 134. 135.]
  [136. 137. 138. 139. 140. 141. 142. 143.]
  [144. 145. 146. 147. 148. 149. 150. 151.]
  [152. 153. 154. 155. 156. 157. 158. 159.]
  [160. 161. 162. 163. 164. 165. 166. 167.]]

 [[168. 169. 170. 171. 1

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
a = np.array([[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]])
np.tile(a, (4, 1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [41]:
ab = np.random.uniform(-10,10, size=(5, 5))
print(ab)

b = round(np.linalg.det(ab), 2)
print(b)

def f(x,de):
    return x/de

for x in range(5):
    for y in range(5):
        ab[x][y] = ab[x][y] / b

print(ab)

[[ 8.36704842  8.48853564 -7.06021979  3.58793156 -0.2264711 ]
 [ 7.40737576 -3.01225886 -5.20607713 -1.36876483 -3.83730188]
 [ 4.40963587 -2.44775191 -7.83756499  7.9154778  -4.60814317]
 [-3.68681492  2.49796883 -9.85459302 -1.01317773 -1.36397018]
 [ 0.06690661  3.16783774 -0.67946296  4.20703966  7.41311662]]
-71047.62
[[-1.17766766e-04 -1.19476707e-04  9.93730654e-05 -5.05003765e-05
   3.18759587e-06]
 [-1.04259309e-04  4.23977448e-05  7.32758835e-05  1.92654565e-05
   5.40102804e-05]
 [-6.20659196e-05  3.44522717e-05  1.10314251e-04 -1.11410879e-04
   6.48599231e-05]
 [ 5.18921664e-05 -3.51590782e-05  1.38704055e-04  1.42605443e-05
   1.91979715e-05]
 [-9.41715019e-07 -4.45875279e-05  9.56348656e-06 -5.92143644e-05
  -1.04340112e-04]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [11]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1),])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
a = np.random.randint(1,5, size=(5,3))
b = np.random.randint(1,5, size=(3,2))
print(a)
print(b)
print(a@b)

[[4 1 3]
 [4 4 4]
 [3 4 2]
 [4 3 3]
 [4 3 3]]
[[2 2]
 [2 1]
 [3 3]]
[[19 18]
 [28 24]
 [20 16]
 [23 20]
 [23 20]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
ab = np.random.randint(5, 15, size=(1))
a = np.random.randint(1,10, size=(ab))
print(a)
for x in range(len(a)):
    if a[x] > 3 and a[x] < 8:
        a[x] *= -1
print(a)

[6 5 8 4 1 2 6 6 3 6 3 3]
[-6 -5  8 -4  1  2 -6 -6  3 -6  3  3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
#9
#10
#Never use *
#np.sum -1 is refering to the axis
#while python sum is just summing and starting the sum at a given value

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [45]:
a = np.random.randint(1,10, size=5)
print(a)
#print(a**a)
#print(2 << a >> 2)
#print(a <- a)
#print(1j*a)
#print(a/1/1)
# cant do print(a<a>a)

[7 6 3 6 4]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [54]:
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array ? (★☆☆)

In [8]:
ab = np.random.uniform(.00001, .0000000000001, size=(5, 5))
print(ab)
np.round(ab)
print('newline')
print(ab)

[[3.40531668e-06 2.40559316e-06 1.45957881e-06 9.08238027e-06
  3.02916591e-06]
 [5.30456490e-06 9.83756823e-06 8.63486500e-06 3.71010322e-06
  4.90052484e-06]
 [5.12414592e-06 2.72094916e-06 7.70408410e-06 1.99718974e-06
  6.22427780e-06]
 [6.39644327e-06 9.20548270e-06 5.87944548e-06 7.54000440e-06
  2.72999134e-06]
 [8.38170688e-06 4.61675509e-06 4.51900412e-06 2.79209291e-06
  4.94267161e-06]]
newline
[[3.40531668e-06 2.40559316e-06 1.45957881e-06 9.08238027e-06
  3.02916591e-06]
 [5.30456490e-06 9.83756823e-06 8.63486500e-06 3.71010322e-06
  4.90052484e-06]
 [5.12414592e-06 2.72094916e-06 7.70408410e-06 1.99718974e-06
  6.22427780e-06]
 [6.39644327e-06 9.20548270e-06 5.87944548e-06 7.54000440e-06
  2.72999134e-06]
 [8.38170688e-06 4.61675509e-06 4.51900412e-06 2.79209291e-06
  4.94267161e-06]]


#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
a = np.random.randint(1,10, size=8)
b = np.random.randint(1,10, size=5)
print(a)
print(b)
c = np.intersect1d(a,b)
print(c)

[8 8 8 9 4 4 9 4]
[6 6 9 4 3]
[4 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [23]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yestraday: ", yesterday, "\nToday: ", today, "\nTomorrow: ", tomorrow)

Yestraday:  2020-11-03 
Today:  2020-11-04 
Tomorrow:  2020-11-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)